//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsa.Properties
{


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dsa.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BinarySearchTreeCollection(Of T) is empty..
        /// </summary>
        internal static string BinarySearchTreeEmpty {
            get {
                return ResourceManager.GetString("BinarySearchTreeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoublyLinkedListCollection(Of T) is empty..
        /// </summary>
        internal static string DoublyLinkedListEmpty {
            get {
                return ResourceManager.GetString("DoublyLinkedListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factorial cannot be called with an integer value less than 0..
        /// </summary>
        internal static string FactorialLessThanZero {
            get {
                return ResourceManager.GetString("FactorialLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibonacci cannot be called with an integer value less than 0..
        /// </summary>
        internal static string FibonacciLessThanZero {
            get {
                return ResourceManager.GetString("FibonacciLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICollection.CopyTo is not supported.  Use the ICollection(Of T).CopyTo method instead..
        /// </summary>
        internal static string ICollectionCopyToNotSupported {
            get {
                return ResourceManager.GetString("ICollectionCopyToNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of item permutations must be greater than 0..
        /// </summary>
        internal static string PermutationsKGreaterThanZero {
            get {
                return ResourceManager.GetString("PermutationsKGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power cannot be called with an exponent less than 0..
        /// </summary>
        internal static string PowerExponentLessThanZero {
            get {
                return ResourceManager.GetString("PowerExponentLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set(Of T) is empty..
        /// </summary>
        internal static string SetEmpty {
            get {
                return ResourceManager.GetString("SetEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SinglyLinkedListCollection(Of T) is empty..
        /// </summary>
        internal static string SinglyLinkedListEmpty {
            get {
                return ResourceManager.GetString("SinglyLinkedListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can only convert positive integers..
        /// </summary>
        internal static string ToBaseNIntNegative {
            get {
                return ResourceManager.GetString("ToBaseNIntNegative", resourceCulture);
            }
        }
    }
}
